#ifndef numerics_h
#define numberics_h

// Standard replies
#define RPL_WELCOME "001"
#define RPL_UNAWAY "305"
#define RPL_NOWAWAY "306"
#define RPL_NAMREPLY "353"
#define RPL_ENDOFNAMES "366"
#define RPL_YOUREOPER "381"

// Errors
#define ERR_UNKNOWNERROR "400"
#define ERR_NOSUCHNICK "401"
#define ERR_NOSUCHCHANNEL "403"
#define ERR_CANNOTSENDTOCHAN "404"
#define ERR_UNKNOWNCOMMAND "421"
#define ERR_NONICKNAMEGIVEN "431"
#define ERR_NICKNAMEINUSE "433"
#define ERR_USERNOTINCHANNEL "441"
#define ERR_NOTONCHANNEL "442"
#define ERR_NOTREGISTERED "451"
#define ERR_NEEDMOREPARAMS "461"
#define ERR_PASSWDMISMATCH "464"
#define ERR_KEYSET "467"
#define ERR_CHANNELISFULL "471"
#define ERR_UNKNOWNMODE "472"
#define ERR_BADCHANNELKEY "475"
#define ERR_NOPRIVILEGES "481"
#define ERR_CHANOPRIVSNEEDED "482"
#define ERR_USERSDONTMATCH "502"

#endif
